"""Add address and account_type

Revision ID: 143d85cea3b9
Revises: 1f6846bbf5a5
Create Date: 2026-09-19 01:28:54.658696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143d85cea3b9'
down_revision: Union[str, Sequence[str], None] = '1f6846bbf5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_type', sa.String(length=20), server_default="Savings", nullable=False))
    op.add_column('customers', sa.Column('address', sa.String(length=500), server_default="", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'address')
    op.drop_column('accounts', 'account_type')
    # ### end Alembic commands ###
