"""initial schema

Revision ID: 7544748d0d97
Revises: 
Create Date: 2026-09-15 16:38:54.060272

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '7544748d0d97'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
